// ================================================================
//  CREATORLINK — themes.js (embedded in index.html)
//  Theme definitions. Variables are applied by app.js.
// ================================================================

const THEMES = {

  // ── CYBER ── neon blue, animated grid, glow orbs, atmospheric
  cyber: {
    bg:          '#020812',
    surface:     'rgba(255,255,255,0.03)',
    border:      'rgba(0,200,255,0.15)',
    accent:      '#00c8ff',
    accentAlt:   '#ff2d78',
    accentTri:   '#a259ff',
    text:        '#e0f4ff',
    muted:       '#4a7a9b',
    fontDisplay: "'Bebas Neue', sans-serif",
    fontBody:    "'Rajdhani', sans-serif",
    fontMono:    "'Share Tech Mono', monospace",
    gridBg:      true,
    glowOrbs:    true,
    scanlines:   true,
    noise:       true,
    cursorRing:  true,
    cursorStyle: 'full',
    nameStyle:   'gradient',
  },

  // ── MINIMAL ── clean white-on-dark, no effects
  minimal: {
    bg:          '#0a0a0a',
    surface:     'rgba(255,255,255,0.04)',
    border:      'rgba(255,255,255,0.1)',
    accent:      '#ffffff',
    accentAlt:   '#888888',
    accentTri:   '#555555',
    text:        '#e8e8e8',
    muted:       '#555555',
    fontDisplay: "'DM Sans', sans-serif",
    fontBody:    "'DM Sans', sans-serif",
    fontMono:    "'DM Mono', monospace",
    gridBg:      false,
    glowOrbs:    false,
    scanlines:   false,
    noise:       false,
    cursorRing:  true,
    cursorStyle: 'minimal',
    nameStyle:   'flat',
  },

  // ── TERMINAL ── green on black, scanlines, old school hacker
  terminal: {
    bg:          '#000000',
    surface:     'rgba(0,255,65,0.03)',
    border:      'rgba(0,255,65,0.2)',
    accent:      '#00ff41',
    accentAlt:   '#00cc33',
    accentTri:   '#009922',
    text:        '#00ff41',
    muted:       '#006614',
    fontDisplay: "'Share Tech Mono', monospace",
    fontBody:    "'Share Tech Mono', monospace",
    fontMono:    "'Share Tech Mono', monospace",
    gridBg:      false,
    glowOrbs:    false,
    scanlines:   true,
    noise:       true,
    cursorRing:  true,
    cursorStyle: 'full',
    nameStyle:   'flat',
  },

  // ── SOFT ── dark purple, pastel accents, vtuber/aesthetic
  soft: {
    bg:          '#0d0a14',
    surface:     'rgba(255,255,255,0.04)',
    border:      'rgba(200,160,255,0.18)',
    accent:      '#c89aff',
    accentAlt:   '#ff9ac8',
    accentTri:   '#9ac8ff',
    text:        '#f0e8ff',
    muted:       '#7a6a8a',
    fontDisplay: "'DM Sans', sans-serif",
    fontBody:    "'DM Sans', sans-serif",
    fontMono:    "'DM Mono', monospace",
    gridBg:      false,
    glowOrbs:    true,
    scanlines:   false,
    noise:       false,
    cursorRing:  true,
    cursorStyle: 'minimal',
    nameStyle:   'gradient',
  },

  // ── SAKURA ── hello kitty pink, deep rose-black bg, soft glow
  sakura: {
    bg:          '#0f0509',
    surface:     'rgba(255,182,193,0.05)',
    border:      'rgba(255,105,180,0.2)',
    accent:      '#ff6eb4',
    accentAlt:   '#ff9ece',
    accentTri:   '#ffb3d9',
    text:        '#ffe8f4',
    muted:       '#8a5070',
    fontDisplay: "'DM Sans', sans-serif",
    fontBody:    "'DM Sans', sans-serif",
    fontMono:    "'DM Mono', monospace",
    gridBg:      false,
    glowOrbs:    true,
    scanlines:   false,
    noise:       true,
    cursorRing:  true,
    cursorStyle: 'minimal',
    nameStyle:   'gradient',
  },

  // ── SUNSET ── warm orange/amber on deep charcoal, retro warm
  sunset: {
    bg:          '#0d0805',
    surface:     'rgba(255,140,0,0.04)',
    border:      'rgba(255,120,50,0.2)',
    accent:      '#ff7c2a',
    accentAlt:   '#ff3d6e',
    accentTri:   '#ffb347',
    text:        '#fff0e0',
    muted:       '#7a5540',
    fontDisplay: "'Bebas Neue', sans-serif",
    fontBody:    "'Rajdhani', sans-serif",
    fontMono:    "'Share Tech Mono', monospace",
    gridBg:      false,
    glowOrbs:    true,
    scanlines:   false,
    noise:       true,
    cursorRing:  true,
    cursorStyle: 'full',
    nameStyle:   'gradient',
  },

  // ── OCEAN ── deep teal/navy, seafoam accents, calm and clean
  ocean: {
    bg:          '#020d12',
    surface:     'rgba(0,200,180,0.04)',
    border:      'rgba(0,210,180,0.15)',
    accent:      '#00d4b4',
    accentAlt:   '#0099cc',
    accentTri:   '#40e0d0',
    text:        '#d0f4f0',
    muted:       '#3a7a7a',
    fontDisplay: "'Bebas Neue', sans-serif",
    fontBody:    "'Rajdhani', sans-serif",
    fontMono:    "'Share Tech Mono', monospace",
    gridBg:      true,
    glowOrbs:    true,
    scanlines:   false,
    noise:       false,
    cursorRing:  true,
    cursorStyle: 'full',
    nameStyle:   'gradient',
  },

  // ── VOID ── pure black, barely-there grey accents, ultra minimal
  void: {
    bg:          '#000000',
    surface:     'rgba(255,255,255,0.02)',
    border:      'rgba(255,255,255,0.06)',
    accent:      '#444444',
    accentAlt:   '#333333',
    accentTri:   '#555555',
    text:        '#aaaaaa',
    muted:       '#333333',
    fontDisplay: "'DM Sans', sans-serif",
    fontBody:    "'DM Sans', sans-serif",
    fontMono:    "'DM Mono', monospace",
    gridBg:      false,
    glowOrbs:    false,
    scanlines:   false,
    noise:       false,
    cursorRing:  true,
    cursorStyle: 'minimal',
    nameStyle:   'flat',
  },

  // ── GOLD ── deep black, luxury gold accents, rich and bold
  gold: {
    bg:          '#080600',
    surface:     'rgba(212,175,55,0.04)',
    border:      'rgba(212,175,55,0.2)',
    accent:      '#d4af37',
    accentAlt:   '#c8960c',
    accentTri:   '#f0d060',
    text:        '#fff8e0',
    muted:       '#7a6a30',
    fontDisplay: "'Bebas Neue', sans-serif",
    fontBody:    "'Rajdhani', sans-serif",
    fontMono:    "'Share Tech Mono', monospace",
    gridBg:      false,
    glowOrbs:    true,
    scanlines:   false,
    noise:       true,
    cursorRing:  true,
    cursorStyle: 'full',
    nameStyle:   'gradient',
  },

};

// Platform accent colours — used for link hover effects
const PLATFORM_COLORS = {
  twitch:    '#9146ff',
  youtube:   '#ff0000',
  twitter:   '#1da1f2',
  instagram: '#e1306c',
  discord:   '#5865f2',
  spotify:   '#1db954',
  github:    '#ffffff',
  tiktok:    '#ff0050',
  reddit:    '#ff4500',
};